/ https://sebastianjones.netlify.app/:splat 200
/about https://sebastianjones.netlify.app/:splat 200
/projects https://sebastianjones.netlify.app/:splat 200
/studies https://sebastianjones.netlify.app/:splat 200
/lessons https://sebastianjones.netlify.app/:splat 200